### ISSUE TITLE
Inconsistent newlines when submitting code in VSCode

### ISSUE THREAD

**Issue by Hong-Revo** [randy3k/radian#102]
I'm using VSCode (on Windows) with Radian, and I've noticed some odd behaviour when submitting code from an R editor window. If I submit a single line by pressing Ctrl-Enter, and that line has blank lines before it, the Radian window will have a varying number of newlines submitted as well.

Here's an example. Say my editor window contains the following, namely some blank lines followed by 1 line of code.

```



"hello"
```

If I then put the cursor on the "hello" and press Ctrl-Enter repeatedly, this is what shows up in Radian. Notice how the submitted code has a varying number of blank lines preceding it. I would expect there to be no blank lines, unless I explicitly select these in the editor window.

This is with @ikuyadeu's vscode-R extension; I'm not sure if this is because of that, or Radian. I'm opening the issue here, because I didn't see this behaviour with the regular R terminal.

![image](https://user-images.githubusercontent.com/11328890/60329597-05be8800-99d4-11e9-89cc-69842d7a33d5.png)

**Comment by andycraig** [comment]
Hi @Hong-Revo, I’m 99% sure this is caused by vscode-r rather than radian, as the vscode-r algorithm that figures out which lines to send does check preceding blank lines. (It’s to see if there are any operators on earlier lines that should be included.) If I’m right, it should be fairly straightforward to fix. I’ll try to have a look into this soon.

**Comment by andycraig** [comment]
This should be resolved now, as of vscode-R v1.1.2.

**Comment by Hong-Revo** [comment]
It's still exhibiting the same behaviour for me....?

Also, I tried changing the new `r.bracketedPaste` setting to `true` as indicated in the v1.1.2 changelog, and this produced errors:

![image](https://user-images.githubusercontent.com/11328890/64700309-fbe3f580-d4e9-11e9-9d72-b9903bc34599.png)

**Comment by Hong-Revo** [comment]
Ok, I set 'Windows enable conpty' to TRUE in settings, and that fixed the errors with `r.bracketedPaste:true`. Still seeing inconsistent newlines though.
