### ISSUE TITLE
Different colors for message, warning, error

### ISSUE THREAD

**Issue by wviechtb** [randy3k/radian#347]
With `options(radian.stderr_format = ...)`, one can set the color for condition signals, which is very nice. But would it be possible to have different colors for messages, warnings, and errors? For example, it would be nice to have something a bit less glaring than red for messages, but still keep errors in red (and maybe something like yellow for messages). Being able to distinguish these different types by color would be quite useful.

**Comment by randy3k** [comment]
It is not possible for now. Though I think you could use tryCatch to catch the messages and print with the desired color.

**Comment by wviechtb** [comment]
Ok, using `globalCallingHandlers()`, I can get this to work:

    message("A message")
    warning("A warning")
    stop("An error")
    
    globalCallingHandlers(
       message = function(c) {
          style <- crayon::make_style("white")
          c$message <- style(c$message)
          message(c)
          invokeRestart("muffleMessage")
       },
       warning = function(c) {
          style <- crayon::make_style("yellow")
          c$message <- style(c$message)
          warning(c)
          invokeRestart("muffleWarning")
       },
       error = function(c) {
          style <- crayon::make_style("red")
          c$message <- style(c$message)
          stop(c)
       }
    )
    
    message("A message")
    warning("A warning")
    stop("An error")

However, for some reason, radian is adding an extra line break after the message even though I have set `options(radian.insert_new_line = FALSE)` (which works correctly for the warning and the error).

**Comment by randy3k** [comment]
@wviechtb 
Thanks for report it, it should be fixed by https://github.com/randy3k/radian/commit/f843d6a2e478e2d3489cdac492f2ede6f5072ca7

**Comment by wviechtb** [comment]
Thanks for looking into this. I just tried this out and I still see an extra new line after a message:

    [10:20] > me@wv > ~/ > pip3 install -U --user git+https://github.com/randy3k/radian
    Collecting git+https://github.com/randy3k/radian
      Cloning https://github.com/randy3k/radian to /tmp/pip-req-build-45lbalzo
      Running command git clone --filter=blob:none --quiet https://github.com/randy3k/radian /tmp/pip-req-build-45lbalzo
      Resolved https://github.com/randy3k/radian to commit f843d6a2e478e2d3489cdac492f2ede6f5072ca7
      Preparing metadata (setup.py) ... done
    Requirement already satisfied: prompt_toolkit<3.1,>=3.0 in ./.local/lib/python3.8/site-packages (from radian==0.6.0) (3.0.29)
    Requirement already satisfied: pygments>=2.5.0 in ./.local/lib/python3.8/site-packages (from radian==0.6.0) (2.9.0)
    Requirement already satisfied: rchitect<0.4.0,>=0.3.36 in ./.local/lib/python3.8/site-packages (from radian==0.6.0) (0.3.36)
    Requirement already satisfied: wcwidth in ./.local/lib/python3.8/site-packages (from prompt_toolkit<3.1,>=3.0->radian==0.6.0) (0.2.5)
    Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from rchitect<0.4.0,>=0.3.36->radian==0.6.0) (1.14.0)
    Requirement already satisfied: cffi>=1.10.0 in ./.local/lib/python3.8/site-packages (from rchitect<0.4.0,>=0.3.36->radian==0.6.0) (1.14.5)
    Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.10.0->rchitect<0.4.0,>=0.3.36->radian==0.6.0) (2.20)
    [10:22] > me@wv > ~/ > radian --quiet --no-history
    
    R version 4.1.3 (2022-03-10) -- One Push-Up
    
    Platform:         x86_64-pc-linux-gnu (64-bit)
    Operating system: Ubuntu 20.04.4 LTS
    Matrix products:  default
    BLAS:             openblas-pthread/libblas.so.3
    LAPACK:           openblas-pthread/liblapack.so.3
    Library path:     ~/rlib/4.1
    Working path:     ~
    
    > message("Test")
    Test
    
    >

Doesn't happen in the standard R console:

    [10:26] > me@wv > ~/ > R
    
    R version 4.1.3 (2022-03-10) -- One Push-Up
    
    Platform:         x86_64-pc-linux-gnu (64-bit)
    Operating system: Ubuntu 20.04.4 LTS
    Matrix products:  default
    BLAS:             openblas-pthread/libblas.so.3
    LAPACK:           openblas-pthread/liblapack.so.3
    Library path:     ~/rlib/4.1
    Working path:     ~
    
    > message("Test")
    Test
    >

**Comment by randy3k** [comment]
Do you still have the option `radian.insert_new_line = FALSE` in `.radian_profile`?
It works for me.
![Screen Shot 2022-04-07 at 4 05 00 PM](https://user-images.githubusercontent.com/1690993/162333559-c9d1b77a-6e66-40a3-b4b1-6a2780652a0b.png)

**Comment by wviechtb** [comment]
Yes, I still have that. But I figured out the problem. I did:

    pip3 install -U --user git+https://github.com/randy3k/radian

to install the devel version, but this actually didn't work. I had to force a reinstall with:

    pip3 install -U --user --force-reinstall git+https://github.com/randy3k/radian

and now it works. Thanks so much!
